steps:
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deploy.yml
  - --image=australia-southeast2-docker.pkg.dev/$PROJECT_ID/task10d/sit737:akshatarora
  - --location=${_CLOUDSDK_COMPUTE_REGION}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
