steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - task10d
  - --project=sit737-23t1-arora-5acc5a5 
  - --region=australia-southeast2
- name: gcr.io/cloud-builders/kubectl
  args:
  - apply
  - -f
  - deploy.yml
